#Vectors

In [1]:
import numpy as np

In [2]:
x = np.ones(3)

In [3]:
x

array([ 1.,  1.,  1.])

In [5]:
y = np.array((2, 4, 6))

In [6]:
y

array([2, 4, 6])

In [7]:
x + y

array([ 3.,  5.,  7.])

In [8]:
4 * x

array([ 4.,  4.,  4.])

In [9]:
np.sum(x * y) #Inner product

12.0

In [10]:
np.sqrt(np.sum(x**2)) #Norm

1.7320508075688772

In [11]:
np.linalg.norm(x) #Norm

1.7320508075688772

#Matrices

In [12]:
import numpy as np

In [15]:
A = ((1, 2),
     (3, 4))

In [16]:
A

((1, 2), (3, 4))

In [17]:
type(A)

tuple

In [18]:
A = np.array(A)

In [19]:
type(A)

numpy.ndarray

In [20]:
A.shape

(2L, 2L)

In [21]:
B = np.identity(3)

In [22]:
B

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
C = np.ones((3,3))

In [24]:
C

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
2 * A

array([[2, 4],
       [6, 8]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [28]:
A = np.array([[1,2], [3,4]])

In [29]:
A

array([[1, 2],
       [3, 4]])

In [30]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [32]:
A.T

array([[1, 3],
       [2, 4]])

In [34]:
np.dot(B, C)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

#Solving Systems of Equations

In [35]:
import numpy as np

In [36]:
from scipy.linalg import inv, solve, det

In [37]:
A = ((1,2), (3,4))

In [38]:
A = np.array(A)

In [39]:
y = np.ones((2,1))

In [40]:
det(A)

-2.0

In [41]:
A_inv = inv(A)

In [43]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [44]:
x = np.dot(A_inv, y)

In [45]:
np.dot(A, x)

array([[ 1.],
       [ 1.]])

In [46]:
solve(A, y)

array([[-1.],
       [ 1.]])

In [47]:
from scipy.linalg import lstsq

In [48]:
lstsq(A, y)

(array([[-1.],
        [ 1.]]),
 array([], dtype=float64),
 2,
 array([ 5.4649857 ,  0.36596619]))

#Eigenvalues and Eigenvectors

In [49]:
from scipy.linalg import eig

In [53]:
A = np.array([[1,2],[2,1]])

In [54]:
evals, evecs = eig(A)

In [55]:
evals

array([ 3.+0.j, -1.+0.j])

In [56]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

#Further Topics

###Neumann’s theorem
If $\|A_k\|<1$ for some $k \in \mathbb{N}$, then $I−A$ is invertible, and
$(I−A)^{−1} = \displaystyle{\sum_{k=0}^\infty A_k}$

###Spectral Radius

For any square matrix A,

$\rho(A) = \lim_{k \to \infty}\|A^k\|^{\frac{1}{k}}$, where $\rho(A) := \max_i |\lambda_i|$